CREATE DATABASE QuanLyHocTap;
GO

USE QuanLyHocTap;
GO

SET DATEFORMAT dmy;
GO


CREATE TABLE VAITRO (
    MAVT  INT IDENTITY(1,1) PRIMARY KEY,
    TENVT NVARCHAR(100) NOT NULL
);

CREATE TABLE KHOA (
    MAKHOA  INT IDENTITY(1,1) PRIMARY KEY,
    TENKHOA NVARCHAR(100) NOT NULL
);

CREATE TABLE NGUOIDUNG (
    MAND      INT IDENTITY(1,1) PRIMARY KEY,
    MAVT      INT NOT NULL,
    MAKHOA    INT,
    TENND     NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU   NVARCHAR(255) NOT NULL,
    TENHT     NVARCHAR(100),
    EMAIL     NVARCHAR(100) UNIQUE,
    SDT       VARCHAR(15),
    TRANGTHAI NVARCHAR(50) CHECK (TRANGTHAI IN (N'Hoạt động', N'Bị khóa')),
    CONSTRAINT FK_ND_VAITRO FOREIGN KEY (MAVT)   REFERENCES VAITRO(MAVT),
    CONSTRAINT FK_ND_KHOA   FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE MONHOC (
    MAMH   INT IDENTITY(1,1) PRIMARY KEY,
    TENMH  NVARCHAR(100) NOT NULL,
    MAKHOA INT NOT NULL,
    CONSTRAINT FK_MH_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE LOPHOC (
    MALH        INT IDENTITY(1,1) PRIMARY KEY,
    MAMH        INT NOT NULL,
    MAND        INT NOT NULL,
    TENLH       NVARCHAR(100) NOT NULL,
    SOSVTOIDA   INT CHECK (SOSVTOIDA > 0),   -- NULL = lớp không giới hạn
    LOAILH      NVARCHAR(50) CHECK (LOAILH IN (N'Online', N'Offline')),
    TRANGTHAI   NVARCHAR(50) CHECK (TRANGTHAI IN (N'Đang mở', N'Đã kết thúc', N'Tạm dừng')),
    NGAYBATDAU  DATE,
    NGAYKETTHUC DATE,
    CONSTRAINT CHK_NgayLH     CHECK (NGAYKETTHUC >= NGAYBATDAU),
    CONSTRAINT FK_LH_MONHOC   FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
    CONSTRAINT FK_LH_GIAOVIEN FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND)
);

CREATE TABLE THAMGIALOP (
    MATHAMGIA  INT IDENTITY(1,1) PRIMARY KEY,
    MALH       INT NOT NULL,
    MAND       INT NOT NULL,
    NGAYDANGKY DATETIME DEFAULT GETDATE(),
    TRANGTHAI  NVARCHAR(50) CHECK (TRANGTHAI IN (N'Đang học', N'Hoàn thành', N'Bỏ học')),
    CONSTRAINT UQ_ThamGia    UNIQUE (MALH, MAND),
    CONSTRAINT FK_TG_LOPHOC  FOREIGN KEY (MALH) REFERENCES LOPHOC(MALH),
    CONSTRAINT FK_TG_HOCSINH FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND)
);


CREATE TABLE LICHHOC (
    MALICH        INT IDENTITY(1,1) PRIMARY KEY,
    MALH          INT NOT NULL,
    THOIGIANBD    TIME NOT NULL,
    THOIGIANKT    TIME NOT NULL,
    HINHTHUC      NVARCHAR(50) CHECK (HINHTHUC IN (N'Online', N'Offline')),
    NGAYHOC       DATE,
    NGAYTRONGTUAN INT,
    CONSTRAINT CHK_ThoiGian        CHECK (THOIGIANKT >= THOIGIANBD),
    CONSTRAINT CHK_NgayTrongTuan   CHECK (NGAYTRONGTUAN IS NULL
                                         OR NGAYTRONGTUAN BETWEEN 2 AND 8),
    CONSTRAINT FK_LichHoc_Lop FOREIGN KEY (MALH) REFERENCES LOPHOC(MALH) ON DELETE CASCADE
);

CREATE TABLE HIENDIEN (
    MAHD         INT IDENTITY(1,1) PRIMARY KEY,
    MATHAMGIA    INT NOT NULL,
    NGAYDIEMDANH DATETIME DEFAULT GETDATE(),
    MALICH       INT NOT NULL,        -- v4: NOT NULL
    TRANGTHAI    NVARCHAR(50) CHECK (TRANGTHAI IN (N'Có mặt', N'Vắng mặt', N'Trễ')),
    CONSTRAINT UQ_HienDien   UNIQUE (MATHAMGIA, MALICH),
    CONSTRAINT FK_HD_THAMGIA FOREIGN KEY (MATHAMGIA) REFERENCES THAMGIALOP(MATHAMGIA),
    CONSTRAINT FK_HD_LICHHOC FOREIGN KEY (MALICH)    REFERENCES LICHHOC(MALICH)
);

CREATE TABLE BAITAP (
    MABT      INT IDENTITY(1,1) PRIMARY KEY,
    MALH      INT NOT NULL,
    MAND      INT NOT NULL,
    TIEUDE    NVARCHAR(255) NOT NULL,
    NOIDUNG   NVARCHAR(MAX),
    HANNOP    DATE,
    NGAYTAO   DATETIME NOT NULL DEFAULT GETDATE(),    -- v4: NOT NULL
    DIEMTOIDA FLOAT NOT NULL CHECK (DIEMTOIDA > 0),   -- NOT NULL để FIX E hoạt động
    CONSTRAINT CHK_HanNopBT    CHECK (HANNOP >= CAST(NGAYTAO AS DATE)),
    CONSTRAINT FK_BT_LOPHOC    FOREIGN KEY (MALH) REFERENCES LOPHOC(MALH) ON DELETE CASCADE,
    CONSTRAINT FK_BT_GIAOVIEN  FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND)
);

CREATE TABLE BAINOP (
    MANOP     INT IDENTITY(1,1) PRIMARY KEY,
    MABT      INT NOT NULL,
    MATHAMGIA INT NOT NULL,
    NGAYNOP   DATETIME DEFAULT GETDATE(),
    DIEM      FLOAT,    -- KHÔNG CHECK [0,10] nữa: điểm raw theo DIEMTOIDA của bài tập
    DUONGDAN  NVARCHAR(255),
    NHANXET   NVARCHAR(MAX),
    CONSTRAINT UQ_BaiNop     UNIQUE (MABT, MATHAMGIA),
    CONSTRAINT FK_BN_BAITAP  FOREIGN KEY (MABT)      REFERENCES BAITAP(MABT),
    CONSTRAINT FK_BN_THAMGIA FOREIGN KEY (MATHAMGIA) REFERENCES THAMGIALOP(MATHAMGIA)
);

CREATE TABLE THONGBAO (
    MATB    INT IDENTITY(1,1) PRIMARY KEY,
    MALH    INT NOT NULL,
    TIEUDE  NVARCHAR(255) NOT NULL,
    NOIDUNG NVARCHAR(MAX),
    NGAYTAO DATETIME DEFAULT GETDATE(),
    MAND    INT,
    CONSTRAINT FK_TB_LOPHOC    FOREIGN KEY (MALH) REFERENCES LOPHOC(MALH) ON DELETE CASCADE,
    CONSTRAINT FK_TB_NGUOIDUNG FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND)
);

CREATE TABLE TINNHAN (
    MATN        INT IDENTITY(1,1) PRIMARY KEY,
    MANGUOIGUI  INT NOT NULL,
    MANGUOINHAN INT NOT NULL,
    NOIDUNG     NVARCHAR(MAX) NOT NULL,
    NGAYGUI     DATETIME DEFAULT GETDATE(),
    DADOC       BIT DEFAULT 0,
    CONSTRAINT CHK_TN_KhacNguoi  CHECK (MANGUOIGUI <> MANGUOINHAN),
    CONSTRAINT FK_TN_NGUOIGUI    FOREIGN KEY (MANGUOIGUI)  REFERENCES NGUOIDUNG(MAND),
    CONSTRAINT FK_TN_NGUOINHAN   FOREIGN KEY (MANGUOINHAN) REFERENCES NGUOIDUNG(MAND)
);

CREATE TABLE BANGDIEM (
    MABD        INT IDENTITY(1,1) PRIMARY KEY,
    MATHAMGIA   INT NOT NULL UNIQUE,
    DIEM        FLOAT CHECK (DIEM >= 0 AND DIEM <= 10),
    XEPLOAI     NVARCHAR(50),
    NGAYCAPNHAT DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_BD_THAMGIA FOREIGN KEY (MATHAMGIA) REFERENCES THAMGIALOP(MATHAMGIA)
);

CREATE TABLE TAILIEU (
    MATL    INT IDENTITY(1,1) PRIMARY KEY,
    TENTL   NVARCHAR(255) NOT NULL,
    MAND    INT NOT NULL,
    MALH    INT NOT NULL,
    TIEUDE  NVARCHAR(255),
    NOIDUNG NVARCHAR(MAX),
    NGAYTAO DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_TL_NGUOIDUNG FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND),
    CONSTRAINT FK_TL_LOPHOC    FOREIGN KEY (MALH) REFERENCES LOPHOC(MALH) ON DELETE CASCADE
);

CREATE TABLE DANHGIA (
    MADG      INT IDENTITY(1,1) PRIMARY KEY,
    MATHAMGIA INT NOT NULL,
    DIEMDG    FLOAT CHECK (DIEMDG >= 0 AND DIEMDG <= 10),
    NHANXET   NVARCHAR(MAX),
    NGAYDG    DATETIME DEFAULT GETDATE(),
    CONSTRAINT UQ_DanhGia    UNIQUE (MATHAMGIA),
    CONSTRAINT FK_DG_THAMGIA FOREIGN KEY (MATHAMGIA) REFERENCES THAMGIALOP(MATHAMGIA)
);


CREATE TABLE CANHBAO (
    MACB    INT IDENTITY(1,1) PRIMARY KEY,
    MAND    INT NOT NULL,
    MALH    INT NOT NULL,
    NGUONCB NVARCHAR(20) NOT NULL                       
            CHECK (NGUONCB IN (N'Điểm', N'Chuyên cần')),
    LOAICB  NVARCHAR(50) CHECK (LOAICB IN (N'Đạt', N'Nguy cơ', N'Nguy cơ cao')),
    NOIDUNG NVARCHAR(MAX),
    NGAYTAO DATETIME DEFAULT GETDATE(),
    DADOC   BIT DEFAULT 0,
    CONSTRAINT UQ_CanhBao       UNIQUE (MAND, MALH, NGUONCB),  -- v4: thêm NGUONCB
    CONSTRAINT FK_CB_NGUOIDUNG  FOREIGN KEY (MAND) REFERENCES NGUOIDUNG(MAND),
    CONSTRAINT FK_CB_LOPHOC     FOREIGN KEY (MALH) REFERENCES LOPHOC(MALH) ON DELETE CASCADE
);
GO



CREATE INDEX IX_ThamGiaLop_MAND  ON THAMGIALOP (MAND);
CREATE INDEX IX_ThamGiaLop_MALH  ON THAMGIALOP (MALH);
CREATE INDEX IX_BaiNop_MATHAMGIA ON BAINOP     (MATHAMGIA);
CREATE INDEX IX_HienDien_MALICH  ON HIENDIEN   (MALICH);
GO

CREATE TRIGGER trg_XoaThamGia
ON THAMGIALOP
INSTEAD OF DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM HIENDIEN  WHERE MATHAMGIA IN (SELECT MATHAMGIA FROM deleted);
    DELETE FROM BAINOP    WHERE MATHAMGIA IN (SELECT MATHAMGIA FROM deleted);
    DELETE FROM BANGDIEM  WHERE MATHAMGIA IN (SELECT MATHAMGIA FROM deleted);
    DELETE FROM DANHGIA   WHERE MATHAMGIA IN (SELECT MATHAMGIA FROM deleted);
    DELETE FROM THAMGIALOP WHERE MATHAMGIA IN (SELECT MATHAMGIA FROM deleted);
END;
GO

CREATE TRIGGER trg_XoaLopHoc
ON LOPHOC
AFTER DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM THAMGIALOP WHERE MALH IN (SELECT MALH FROM deleted);
END;
GO


CREATE TRIGGER trg_KiemTraVaiTroLopHoc
ON LOPHOC AFTER INSERT, UPDATE
AS BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 FROM inserted i
        JOIN NGUOIDUNG nd ON i.MAND = nd.MAND
        JOIN VAITRO vt    ON nd.MAVT = vt.MAVT
        WHERE vt.TENVT != N'Giáo viên'
    ) BEGIN
        RAISERROR (N'Người tạo lớp học phải có vai trò Giáo viên.', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

CREATE TRIGGER trg_KiemTraVaiTroBaiTap
ON BAITAP AFTER INSERT, UPDATE
AS BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 FROM inserted i
        JOIN NGUOIDUNG nd ON i.MAND = nd.MAND
        JOIN VAITRO vt    ON nd.MAVT = vt.MAVT
        WHERE vt.TENVT != N'Giáo viên'
    ) BEGIN
        RAISERROR (N'Người tạo bài tập phải có vai trò Giáo viên.', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

CREATE TRIGGER trg_KiemTraVaiTroTaiLieu
ON TAILIEU AFTER INSERT, UPDATE
AS BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 FROM inserted i
        JOIN NGUOIDUNG nd ON i.MAND = nd.MAND
        JOIN VAITRO vt    ON nd.MAVT = vt.MAVT
        WHERE vt.TENVT != N'Giáo viên'
    ) BEGIN
        RAISERROR (N'Người tạo tài liệu phải có vai trò Giáo viên.', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

CREATE TRIGGER trg_KiemTraVaiTroThamGia
ON THAMGIALOP AFTER INSERT, UPDATE
AS BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1 FROM inserted i
        JOIN NGUOIDUNG nd ON i.MAND = nd.MAND
        JOIN VAITRO vt    ON nd.MAVT = vt.MAVT
        WHERE vt.TENVT != N'Học sinh'
    ) BEGIN
        RAISERROR (N'Người tham gia lớp học phải có vai trò Học sinh.', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO


CREATE TRIGGER trg_KiemTraSiSo
ON THAMGIALOP AFTER INSERT
AS BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN LOPHOC lh ON i.MALH = lh.MALH
        WHERE lh.SOSVTOIDA IS NOT NULL
          AND (SELECT COUNT(*) FROM THAMGIALOP WHERE MALH = i.MALH) > lh.SOSVTOIDA
    ) BEGIN
        RAISERROR (N'Lớp học đã đạt số lượng học viên tối đa.', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

CREATE TRIGGER trg_KiemTraDiemBaiNop
ON BAINOP AFTER INSERT, UPDATE
AS BEGIN
    SET NOCOUNT ON;
    IF NOT UPDATE(DIEM) RETURN;

    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN BAITAP bt ON bt.MABT = i.MABT
        WHERE i.DIEM IS NOT NULL
          AND (i.DIEM < 0 OR i.DIEM > bt.DIEMTOIDA)
    ) BEGIN
        RAISERROR (N'Điểm bài nộp phải nằm trong khoảng [0, DIEMTOIDA của bài tập].', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO


CREATE TRIGGER trg_TinhBangDiem
ON BAINOP
AFTER INSERT, UPDATE  
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT UPDATE(DIEM) RETURN;

    IF NOT EXISTS (SELECT 1 FROM inserted WHERE DIEM IS NOT NULL) RETURN;

    ;WITH AffectedTG AS (
        SELECT DISTINCT MATHAMGIA FROM inserted
    ),
    DiemTongKet AS (
        SELECT
            a.MATHAMGIA,
            AVG(bn.DIEM * 10.0 / NULLIF(bt.DIEMTOIDA, 0)) AS DIEM_TONGKET
        FROM AffectedTG a
        JOIN BAINOP bn ON bn.MATHAMGIA = a.MATHAMGIA
        JOIN BAITAP bt ON bt.MABT      = bn.MABT
        WHERE bn.DIEM IS NOT NULL
        GROUP BY a.MATHAMGIA
    )
    MERGE BANGDIEM AS bd
    USING DiemTongKet AS dtk
        ON bd.MATHAMGIA = dtk.MATHAMGIA
    WHEN MATCHED THEN
        UPDATE SET
            bd.DIEM        = dtk.DIEM_TONGKET,
            bd.XEPLOAI     = CASE
                                WHEN dtk.DIEM_TONGKET >= 8.5 THEN N'Giỏi'
                                WHEN dtk.DIEM_TONGKET >= 7.0 THEN N'Khá'
                                WHEN dtk.DIEM_TONGKET >= 5.0 THEN N'Trung bình'
                                ELSE N'Yếu'
                             END,
            bd.NGAYCAPNHAT = GETDATE()
    WHEN NOT MATCHED THEN
        INSERT (MATHAMGIA, DIEM, XEPLOAI, NGAYCAPNHAT)
        VALUES (
            dtk.MATHAMGIA,
            dtk.DIEM_TONGKET,
            CASE
                WHEN dtk.DIEM_TONGKET >= 8.5 THEN N'Giỏi'
                WHEN dtk.DIEM_TONGKET >= 7.0 THEN N'Khá'
                WHEN dtk.DIEM_TONGKET >= 5.0 THEN N'Trung bình'
                ELSE N'Yếu'
            END,
            GETDATE()
        );
END;
GO


CREATE TRIGGER trg_CapNhatCanhBao
ON BANGDIEM
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT UPDATE(DIEM) RETURN;

    ;WITH CanhBaoMoi AS (
        SELECT
            tg.MAND,
            tg.MALH,
            CASE
                WHEN i.DIEM >= 5 THEN N'Đạt'
                WHEN i.DIEM >= 3 THEN N'Nguy cơ'
                ELSE N'Nguy cơ cao'
            END AS LOAI,
            N'Điểm tổng kết: '
              + ISNULL(CAST(ROUND(i.DIEM, 2) AS NVARCHAR(10)), N'Chưa có')
              + N' — Phân loại: '
              + CASE
                    WHEN i.DIEM >= 5 THEN N'Đạt'
                    WHEN i.DIEM >= 3 THEN N'Nguy cơ'
                    ELSE N'Nguy cơ cao'
                END AS NOIDUNG
        FROM inserted i
        JOIN THAMGIALOP tg ON i.MATHAMGIA = tg.MATHAMGIA
        WHERE i.DIEM IS NOT NULL
    )
    MERGE CANHBAO AS cb
    USING CanhBaoMoi AS cbm
        ON cb.MAND = cbm.MAND
       AND cb.MALH = cbm.MALH
       AND cb.NGUONCB = N'Điểm'      
    WHEN MATCHED THEN
        UPDATE SET
            cb.LOAICB  = cbm.LOAI,
            cb.NOIDUNG = cbm.NOIDUNG,
            cb.NGAYTAO = GETDATE(),
            cb.DADOC   = 0
    WHEN NOT MATCHED THEN
        INSERT (MAND, MALH, NGUONCB, LOAICB, NOIDUNG, NGAYTAO, DADOC)
        VALUES (cbm.MAND, cbm.MALH, N'Điểm', cbm.LOAI, cbm.NOIDUNG, GETDATE(), 0);
END;
GO


CREATE TRIGGER trg_CanhBaoVangHoc
ON HIENDIEN
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    ;WITH AffectedTG AS (
        SELECT DISTINCT MATHAMGIA FROM inserted   
    ),
    TyLeVang AS (
        SELECT
            tg.MAND,
            tg.MALH,
            COUNT(*)                                                    AS TONG_BUOI,
            SUM(CASE WHEN hd.TRANGTHAI = N'Vắng mặt' THEN 1 ELSE 0 END) AS SO_VANG,
            CAST(SUM(CASE WHEN hd.TRANGTHAI = N'Vắng mặt' THEN 1 ELSE 0 END) AS FLOAT)
                / NULLIF(COUNT(*), 0)                                   AS TY_LE_VANG
        FROM AffectedTG a
        JOIN THAMGIALOP tg ON a.MATHAMGIA = tg.MATHAMGIA
        JOIN HIENDIEN hd   ON hd.MATHAMGIA = tg.MATHAMGIA
        GROUP BY tg.MAND, tg.MALH
    ),
    CanhBaoVang AS (
        SELECT
            MAND, MALH,
            CASE
                WHEN TY_LE_VANG > 0.4 THEN N'Nguy cơ cao'
                WHEN TY_LE_VANG > 0.2 THEN N'Nguy cơ'
                ELSE N'Đạt'
            END AS LOAI_VANG,
            N'Tỷ lệ vắng học: '
              + CAST(ROUND(TY_LE_VANG * 100, 1) AS NVARCHAR(10)) + N'%'
              + N' (' + CAST(SO_VANG AS NVARCHAR(5))
              + N'/' + CAST(TONG_BUOI AS NVARCHAR(5)) + N' buổi)' AS NOIDUNG_VANG
        FROM TyLeVang
    )
    MERGE CANHBAO AS cb
    USING CanhBaoVang AS cbv
        ON cb.MAND = cbv.MAND
       AND cb.MALH = cbv.MALH
       AND cb.NGUONCB = N'Chuyên cần'       
    WHEN MATCHED THEN
        UPDATE SET
            cb.LOAICB  = cbv.LOAI_VANG,
            cb.NOIDUNG = cbv.NOIDUNG_VANG,
            cb.NGAYTAO = GETDATE(),
            cb.DADOC   = 0
    WHEN NOT MATCHED THEN
        INSERT (MAND, MALH, NGUONCB, LOAICB, NOIDUNG, NGAYTAO, DADOC)
        VALUES (cbv.MAND, cbv.MALH, N'Chuyên cần', cbv.LOAI_VANG, cbv.NOIDUNG_VANG, GETDATE(), 0);
END;
GO


CREATE TRIGGER trg_KiemTraThoiGianLichHoc
ON LICHHOC AFTER INSERT, UPDATE
AS BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM inserted WHERE THOIGIANKT < THOIGIANBD) BEGIN
        RAISERROR (N'Thời gian kết thúc không được trước thời gian bắt đầu.', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

